### ISSUE TITLE
Issue when starting

### ISSUE THREAD

**Issue by SlickTorpedo** [spyoungtech/voice-commander#2]
![image](https://user-images.githubusercontent.com/55722867/151714065-a8315790-fcc4-4454-a5ca-3bcaafd45a09.png)

How do I fix this?

**Comment by spyoungtech** [comment]
Hi @SlickTorpedo  

You'll have to install the [required modules](https://github.com/spyoungtech/voice-commander/blob/master/setup.py#L7). Easiest way to install is using `pip` which will include the dependencies.

Install from PyPI:

```bash
pip install voice-commander
```

or from a local clone of this repo:

```bash
git clone https://github.com/spyoungtech/voice-commander.git voice-commander
cd voice-commander
pip install -E .
```

Or, I suppose, you can install the requirements independently:


```
pip install fuzzywuzzy "fuzzywuzzy[speedup]" keyboard easygui pyaudio SpeechRecognition
```

**Comment by SlickTorpedo** [comment]
> Owner

Alright i'll look into that thank you!
